namespace Alundra.Gameplay;

public class Voice {
    byte volLeft;
    byte _1;
    byte _2;
    byte _3;
    byte pitch;
    byte _5;
    byte reverbDepth;
    byte _7;
    byte adsrAttack;
    byte _9;
    byte adsrSustain;
    byte _b;
    byte status;
    byte[] _d = new byte[3];
    Voice[] nextVoice;
    byte[] _14 = new byte[359];
    short _17b;
    short _17d;
    short _17f;
    short _181;
    byte[] _183 = new byte[5];
    short _188;
    short _18a;
    byte _18c;
    byte _18d;
    short _18e;
    int _190;
    ushort _194;
    ushort _196;
    short _198;
    short _19a;
    byte[] _19c = new byte[14];
    ushort _1aa;
};